### ISSUE TITLE
 Cannot read property 'createValueMap' of undefined

### ISSUE THREAD

**Issue by pvsong** [w3tecch/express-typescript-boilerplate#115]
TypeError: Cannot read property 'createValueMap' of undefined: 3c83fe6e-17d8-489d-8300-45aba1053f2b
    at MongoDriver.createGeneratedMap (/Users/user/STORAGE/types/src/driver/mongodb/MongoDriver.ts:323:41)
    at /Users/user/STORAGE/types/src/entity-manager/MongoEntityManager.ts:190:66
    at Array.forEach (<anonymous>)
    at MongoEntityManager.<anonymous> (/Users/user/STORAGE/types/src/entity-manager/MongoEntityManager.ts:188:49)
    at step (/Users/user/STORAGE/types/node_modules/typeorm/entity-manager/MongoEntityManager.js:42:23)
    at Object.next (/Users/user/STORAGE/types/node_modules/typeorm/entity-manager/MongoEntityManager.js:23:53)
    at fulfilled (/Users/user/STORAGE/types/node_modules/typeorm/entity-manager/MongoEntityManager.js:14:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

mongodb version: 3.0.15
node: v10.8.0
typeorm: 0.2.7

**Comment by pvsong** [comment]
Fixed by add @ObjectIdColumn() in id

**Comment by hs2504785** [comment]
@PrimaryGeneratedColumn()
  id: number;

update to 

  @ObjectIdColumn()
  id: number;
