### ISSUE TITLE
Webpack bundling issue

### ISSUE THREAD

**Issue by gottipatibalu** [w3tecch/express-typescript-boilerplate#163]
I having issues bundling this with webpack

**Warning when bundling with webpack**

WARNING in ./node_modules/app-root-path/lib/app-root-path.js 14:10-56
Critical dependency: the request of a dependency is an expression
@ ./node_modules/app-root-path/index.js
@ ./node_modules/microframework/Microframework.js
@ ./node_modules/microframework/index.js
@ ./app.ts

WARNING in ./node_modules/microframework/Microframework.js
Module not found: Error: Can't resolve 'ascii-art' in '/Users/bgottip/Desktop/template/nodeproj/node_modules/microframework'
@ ./node_modules/microframework/Microframework.js
@ ./node_modules/microframework/index.js
@ ./app.ts

**Error when running the file using node**

node dist/server.js
path.js:39
throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
at assertPath (path.js:39:11)
at Object.dirname (path.js:1265:5)
at resolve (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:615:22)
at module.exports (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:497:20)
at Object.module.exports (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:485:18)
at webpack_require (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:20:30)
at Microframework.config (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:204:26)
at Object.bootstrapMicroframework (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:163:10)
at Object.defineProperty.value (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:115:18)
at webpack_require (/Users/bgottip/Desktop/template/nodeproj/dist/server.js:20:30)

any ideas? anyone using this webpack ?

**Comment by Paul75** [comment]
I have the same problem and not found solutions
