### ISSUE TITLE
Cannot set headers after they are sent - authorizationChecker called twice?

### ISSUE THREAD

**Issue by wallopthecat** [w3tecch/express-typescript-boilerplate#174]
Using develop branch, bruce:1234 as creds, calling `api/users/me` results in this:
```
info: [auth:AuthService] Credentials provided by the client
info: [auth:authorizationChecker] Successfully checked credentials
info: [auth:AuthService] Credentials provided by the client
info: [api:middlewares] GET /api/users/me 200 97.256 ms - 147

info: [auth:authorizationChecker] Successfully checked credentials
info: [api:services\UserService] Find one user
Error [ERR_HTTP_HEADERS_SENT] [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (node_modules\express\lib\response.js:767:10)
    at ServerResponse.send (node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (node_modules\express\lib\response.js:267:15)
    at ErrorHandlerMiddleware.error (src\api\middlewares\ErrorHandlerMiddleware.ts:18:13)
    at src\driver\express\ExpressDriver.ts:60:74
    at Layer.handle_error (node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (node_modules\express\lib\router\index.js:315:13)
    at node_modules\express\lib\router\index.js:284:7
    at Function.process_params (node_modules\express\lib\router\index.js:335:12)
```

```
curl -X GET \
  http://localhost:3000/api/users/me \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Basic YnJ1Y2U6MTIzNA==' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Host: localhost:3000' \
  -H 'cache-control: no-cache'
```

**Comment by wallopthecat** [comment]
Fixed by adding a regex to `@Get('/:id')` in `UserController`

Route handler was matching both routes, causing the error
