### ISSUE TITLE
Socket IO Integration

### ISSUE THREAD

**Issue by jasonvillalon** [w3tecch/express-typescript-boilerplate#24]
Hi, 

Ive been using this boilerplate for a while. now im integrating socket.io but noticed weird behavior. i tried to remove my integration and looks like the server still accepts socket connection. is there a ready socket integration in this boilerplate? im keep on digging but cant find anything which is weird.

Best Regards,
Jason Villalon

**Comment by jasonvillalon** [comment]
nvm. looks like express-status-monitor.

**Comment by Paul75** [comment]
Hello,

that means can't use socket.io ?

I want to add possibility to send to Angular and found socket.io solution ?

Thanks

**Comment by michaelholstdev** [comment]
Hello, its possible. You must override the express-monitor socket. 
I get it running with:

webSocketLoader.ts
```
export default  () => {
     const io = require('socket.io')(5000, {
     origins: "*:*",
     handlePreflightRequest: (req, res) => {
            const headers = {
                'Access-Control-Allow-Headers': 'Content-Type, Authorization',
                'Access-Control-Allow-Origin': req.headers.origin,
                'Access-Control-Allow-Credentials': true,
            };
            res.writeHead(200, headers);
            res.end();
        },
    });
    io.on('connection', (socket: any) => {
        console.log('hello World', socket);
    });
    return io;
};
```

monitorLoader.ts
```
...
expressApp.use(monitor({
            websocket: websocketLoader(),
        }));
...
```

**Comment by Paul75** [comment]
Hello,

thanks bug have error :

```
error: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Server.listen.Server.attach (/Users/laposte/Projets/crous78/crous-drive/drive-server/node_modules/socket.io/lib/index.js:273:9)
    at new Server (/Users/laposte/Projets/crous78/crous-drive/drive-server/node_modules/socket.io/lib/index.js:59:17)
    at Server (/Users/laposte/Projets/crous78/crous-drive/drive-server/node_modules/socket.io/lib/index.js:44:41)
    at Object.exports.default (/Users/laposte/Projets/crous78/crous-drive/drive-server/src/loaders/webSocketLoader.ts:2:36)
    at exports.monitorLoader (/Users/laposte/Projets/crous78/crous-drive/drive-server/src/loaders/monitorLoader.ts:14:39)
    at /Users/laposte/Projets/crous78/crous-drive/src/Microframework.ts:110:42
    at /Users/laposte/Projets/crous78/crous-drive/src/Microframework.ts:158:24 {"error":{"code":"EADDRINUSE","errno":"EADDRINUSE","syscall":"listen","address":"::","port":5000},"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (net.js:1313:16)\n    at listenInCluster (net.js:1361:12)\n    at Server.listen (net.js:1449:7)\n    at Server.listen.Server.attach (/Users/laposte/Projets/crous78/crous-drive/drive-server/node_modules/socket.io/lib/index.js:273:9)\n    at new Server (/Users/laposte/Projets/crous78/crous-drive/drive-server/node_modules/socket.io/lib/index.js:59:17)\n    at Server (/Users/laposte/Projets/crous78/crous-drive/drive-server/node_modules/socket.io/lib/index.js:44:41)\n    at Object.exports.default (/Users/laposte/Projets/crous78/crous-drive/drive-server/src/loaders/webSocketLoader.ts:2:36)\n    at exports.monitorLoader (/Users/laposte/Projets/crous78/crous-drive/drive-server/src/loaders/monitorLoader.ts:14:39)\n    at /Users/laposte/Projets/crous78/crous-drive/src/Microframework.ts:110:42\n    at /Users/laposte/Projets/crous78/crous-drive/src/Microframework.ts:158:24","exception":true,"date":"Mon May 04 2020 00:11:30 GMT+0200 (Central European Summer Time)","process":{"pid":74247,"uid":501,"gid":20,"cwd":"/Users/laposte/Projets/crous78/crous-drive/drive-server","execPath":"/usr/local/bin/node","version":"v12.16.2","argv":["/usr/local/bin/node","/Users/laposte/Projets/crous78/crous-drive/drive-server/src/app.ts"],"memoryUsage":{"rss":106434560,"heapTotal":78548992,"heapUsed":48786768,"external":2121155}},"os":{"loadavg":[1.8798828125,2.06103515625,1.974609375],"uptime":1854762},"trace":[{"column":16,"file":"net.js","function":"Server.setupListenHandle [as _listen2]","line":1313,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"net.js","function":"listenInCluster","line":1361,"method":null,"native":false},{"column":7,"file":"net.js","function":"Server.listen","line":1449,"method":"listen","native":false},{"column":9,"file":"/Users/laposte/Projets/crous78/crous-drive/drive-server/node_modules/socket.io/lib/index.js","function":"Server.listen.Server.attach","line":273,"method":"attach","native":false},{"column":17,"file":"/Users/laposte/Projets/crous78/crous-drive/drive-server/node_modules/socket.io/lib/index.js","function":"new Server","line":59,"method":null,"native":false},{"column":41,"file":"/Users/laposte/Projets/crous78/crous-drive/drive-server/node_modules/socket.io/lib/index.js","function":"Server","line":44,"method":null,"native":false},{"column":36,"file":"/Users/laposte/Projets/crous78/crous-drive/drive-server/src/loaders/webSocketLoader.ts","function":"Object.exports.default","line":2,"method":"default","native":false},{"column":39,"file":"/Users/laposte/Projets/crous78/crous-drive/drive-server/src/loaders/monitorLoader.ts","function":"exports.monitorLoader","line":14,"method":"monitorLoader","native":false},{"column":42,"file":"/Users/laposte/Projets/crous78/crous-drive/src/Microframework.ts","function":null,"line":110,"method":null,"native":false},{"column":24,"file":"/Users/laposte/Projets/crous78/crous-drive/src/Microframework.ts","function":null,"line":158,"method":null,"native":false}]}
```

**Comment by Paul75** [comment]
Hello,

Thanks but now when I launch program I have : 

`info: [api:middlewares] GET /socket.io/?EIO=3&transport=polling&t=N7SesEw 404 0.789 ms - 149`

Sorry but I seams to use socket.io to send notificaion when I do action like for exemple after count liens of datatable and it take more than a number I send to Angular info and after in angular I want to receive and do something.

I'm write, I must use socket.io ?

Thanks

**Comment by gualtierim** [comment]
Hi,
you can try to use the angular module: ng-socket-io.

I made it works using these options:
```
const options = {
    reconnection: true,
    reconnectionDelay: 1000,
    reconnectionDelayMax: 5000,
    reconnectionAttempts: Infinity,
    multiplex: false,
    path: environment.ws_path,
    transports: ['websocket']
};

const config: SocketIoConfig = { url: url, options: options };
````
I configured the socket.io like described by: @ZeroCool-85 .

**Comment by Paul75** [comment]
Thanks.

And in controller or service when I send (emit ?) message and data to angular ? When I call socket ?

Thanks

**Comment by gualtierim** [comment]
You can write a Service to emit message in the websocket.

```
import { Injectable } from '@angular/core';
import { Socket } from 'ng-socket-io';

@Injectable()
export class SocketService {

  constructor(
    private socket: Socket,
  ) {
    socket.on('connect', () => {
          ....
    });
  }

  public sendMessage(messageName: string, msg: any) {
    this.socket.emit(messageName, msg);
  }

  public getMessage<T = any>(event: string) {
    return this.socket
      .fromEvent<T>(event);
  }

  public removeListener(event: string) {
    this.socket.removeListener(event);
  }

}

```

**Comment by Paul75** [comment]
Hello,

Thanks but that if to send Angular to Backend but in Backend to Angular ?

Thanks
