### ISSUE TITLE
Can't setup on windows

### ISSUE THREAD

**Issue by vincaslt** [w3tecch/express-typescript-boilerplate#5]
On windows I'm getting and error when running `npm run setup`:

```
C:\Users\Vincas\Desktop\express-typescript-boilerplate\node_modules\.bin\knex:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at Object.<anonymous> (C:\Users\Vincas\Desktop\express-typescript-boilerplate\node_modules\ts-node\src\_bin.ts:180:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

Looks like it is trying to execute .sh script on windows and can't make out the syntax

**Comment by lubej** [comment]
See this issue:
#2

**Comment by vincaslt** [comment]
Hmm, I seem to be getting the same error on the branch: `feature/fix-windows-issues` in CMD and in Bash...

**Comment by dweber019** [comment]
@vincaslt branch `feature/fix-windows-issues` has no more fixes including this issue.
Issues left:
- Tests (unit and blackbox) => 
- Regression tests for unix on branch `feature/fix-windows-issues`

I will create a new bug for testing on windows.
